# -*- coding: utf-8 -*-
"""Movie_Recommendation_System.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1vy-CYkdVOPFDNN1aK86BvbQpIMqtMIHa

Dataset Location:Desktop/Machine Learning/Movie Recommandation System/.. <br>
Movie Recommender System Project | Content Based Recommender System with Heroku Deployment<br>
Video:https://youtu.be/1xtrIEwY_zY?si=MAAzYVEQYvF1X2ju<br>

1. Importing Dependant Libraries.
"""

#Importing Libraries
import numpy as np
import pandas as pd

#Import Datasets
movies=pd.read_csv('tmdb_5000_movies.csv')
credits=pd.read_csv('tmdb_5000_credits.csv')

"""2. Now You have Two Datasets one is Movies List and Credits of that move Merge two datasets to one Dataset"""

movies.head(1)
#movies.shape

credits.head(1)
#credits.shape

# two add both the dataset we have common column that is title & movies.id, movies.id = credits.movie_id since both columns represent the same movie, even though their names are different.
# we add using title
movies=movies.merge(credits,on='title')

movies.head(1)

"""3. Featuring Enginerring & Data Preprocessing."""

movies.info()
# Nessary Data Remaining all Deleting.
#genres
#movie_id
#keywords
#title
#overview
#cast
#crew
movies=movies[['movie_id','title','overview','genres','keywords','cast','crew']]

movies.head(3)
movies.isnull().sum()

#Removing Duplicates
movies.duplicated().sum()

#Feature Engineering
#Creating a Single tag column that contains overview + genres + keywords + cast+ crew

#for genres(Selecting only names)
movies.iloc[0].genres

import ast
def convert(obj):
  L =[]
  for i in ast.literal_eval(obj):
    L.append(i['name'])
  return L
  #for 1st Iteration i = {'id': 28, 'name': 'Action'}
  #for 2nd Iteration i = {'id': 12, 'name': 'Adventure'}
  #for 3rd Iteration i = {'id': 14, 'name': 'Fantasy'}

movies['genres']=movies['genres'].apply(convert)
movies.head(3)

#for keywords (selecting names)
movies.iloc[0].keywords
movies['keywords']=movies['keywords'].apply(convert)
movies.head(3)

#for cast
movies['cast'][0]
#the output if for only one movies. In these there are so many character but we need only top three actual names.

import ast

def convert1(obj):
    L = []

    # Convert only if it's a string
    if isinstance(obj, str):
        obj = ast.literal_eval(obj)
        #Example: "[{'name': 'Sam'}, {'name': 'Zoe'}, {'name': 'Sigourney'}]" to [{'name': 'Sam'}, {'name': 'Zoe'}, {'name': 'Sigourney'}]
    # " " are removed.


    # Loop first 3 items
    for i in obj[:3]:

        # Case 1: dictionary
        if isinstance(i, dict):
            L.append(i.get('name', ''))

        # Case 2: string
        elif isinstance(i, str):
            L.append(i)

    return L

movies['cast']=movies['cast'].apply(convert1)
movies.head()

#for Crew
movies['crew'][0]

# in crew you only need director from every movie.
#if job == director we need that director name.
def fretch_director(obj):
  L=[]
  for i in ast.literal_eval(obj):
    if i['job']=='Director':
      L.append(i['name'])
      break
  return L

movies['crew']=movies['crew'].apply(fretch_director)

movies.head(5)

#Now convert the Overview to string to list then merge all remaing rows to overview so that we have only three columns
#Id Title Overview
movies['overview'] = movies['overview'].fillna('')
movies['overview']=movies['overview'].apply(lambda x:x.split())

#Also you need to replace " " to "" in every columns geners,keyword, all that
movies['genres']=movies['genres'].apply(lambda x:[i.replace(" ","") for i in x])
movies['keywords']=movies['keywords'].apply(lambda x:[i.replace(" ","") for i in x])
movies['crew']=movies['crew'].apply(lambda x:[i.replace(" ","") for i in x])
movies['cast']=movies['cast'].apply(lambda x:[i.replace(" ","") for i in x])

#Merge all these into a column name called tags
movies['tags']=movies['overview']+movies['genres']+movies['keywords']+movies['cast']+movies['crew']
new_df=movies[['movie_id','title','tags']]

"""Your Data is Cleaned & Preprocessed"""

movies.head(3)

new_df['tags']=new_df['tags'].apply(lambda x:" ".join(x))
new_df['tags'][0]

new_df['tags']=new_df['tags'].apply(lambda x:x.lower())

new_df.head()

"""4. PorterStemmer <br>
This will help in simalar words conversion<br>
Example: <br>
['lover','loves','loved','love','loving']<br>
['love','love','love','love','love']
"""

import nltk
from nltk.stem.porter import PorterStemmer
ps=PorterStemmer()

def stem(text):
  y=[]
  for i in text.split():
     y.append(ps.stem(i))
  return " ".join(y)

#apply function will work as for loop, for each row the function will be called.
new_df['tags']=new_df['tags'].apply(stem)
new_df.head()

"""5. Vectorization

Machines only understand numbers. Vectorization is the translator.
Every type of raw data — whether it's text, images, video, audio, or anything else — gets converted into numbers (vectors) so that machine learning models can understand and process it.

Example:<br>
Text    "Hello World"        →   [0.2, 0.8, -0.3, 0.5, ...]<br>
Image   (a photo of a cat)  →   [255, 230, 128, 0, 45, ...]<br>
Video   (a movie clip)      →   [frames → each frame → pixels → numbers]<br>
Audio   (a song / voice)    →   [frequency values → [0.4, 0.1, 0.9, ...]]<br>
Number  Age = 25            →   [25] or scaled → [0.25]<br>
Category "Red"              →   [1, 0, 0]
"""

#Listen Vectorization in Movie Recommandation System || Campusx
from sklearn.feature_extraction.text import CountVectorizer
cv=CountVectorizer(max_features=5000,stop_words='english')

#max_feature:Keep only top 5000 most used words in entire movie dataset
#stop_words: like in, and, a, of, an will not be added these are connecting words in english

"""
“max_features=5000 means from all the tags it will take Top 5000 most frequent unique words”
✅ Correct

“then for each movie the frequency of the word will be counted”
✅ Partially correct — but let’s refine it

🔹 Correct Understanding (important)
Step 1: Build vocabulary (global)
👉 From ALL movies combined, it selects:
Top 5000 most frequent unique words
✔ This happens once globally, not per movie

Step 2: For each movie
👉 Now for each movie, it checks:
“How many times does each of those 5000 words appear in this movie?”"""

#It converts all movie tags (text) into numerical vectors (matrix form)
#[
# [0,1,0,2,0,...],   ← Movie 1
# [1,0,0,0,3,...],   ← Movie 2
# [0,0,1,1,0,...],   ← Movie 3
# ...
#]
vector=cv.fit_transform(new_df['tags']).toarray()
vector
#👉 Both happen together:
#fit() → learns words
#transform() → convert all the points to numerical values & creates vectors

cv.get_feature_names_out()

"""6. Similarity between Movies<br>
Compares every movie with every movie<br>
👉 Shape = (4809, 4809)<br> every vector with every vector
"""

from sklearn.metrics.pairwise import cosine_similarity
similarity=cosine_similarity(vector)
similarity.shape
similarity[0]

#sorted(list(enumerate(similarity[0])),reverse=True,key=lambda x:x[1])[1:6]

"""7. Movie Recommended Function<br>
This will give you the similar movies

Here is the logic:
<br>
When I search for a movie (for example, Avatar), first I find its index (or movie ID) in the dataset. Then I take the vector of that movie and use cosine similarity to compare it with all other movie vectors.
<br>
This gives similarity scores between the selected movie and every other movie. After that, I sort these scores in descending order and select the top 5 highest values (excluding the movie itself).
"""

# Search the given movie name in the title column
# Pandas checks all movie titles and finds the matching row
# Get the index of that matched movie
# This index is used to access its similarity scores

def recommend(movie):
  movie_index=new_df[new_df['title']== movie].index[0]
  movies_list=sorted(list(enumerate(similarity[movie_index])),reverse=True,key=lambda x:x[1])[1:6]

  L=[]
  for i in movies_list:
    print(new_df.iloc[i[0]].title)
    L.append(new_df.iloc[i[0]].title)

recommend('Batman Begins')

new_df.iloc[1214]

new_df.iloc[1214].title

"""Your ML Model is Ready"""

import pickle
pickle.dump(new_df,open('movies.pkl','wb'))

pickle.dump(similarity,open('similarity.pkl','wb'))

"""This Project is Completed and Uploaded in GitHub<br>
GitHub Link:<br>
Demo Link:<br>
"""